version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 143143143@Sk
      MYSQL_DATABASE: golfclub_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  golfclub-api:
    build: .
    container_name: golfclub-api
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql-data:
